name: patta
description: A new Flutter project.

# Docs:
# https://docs.codemagic.io/configuration/build-versioning/
# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# We use Codemagic automatic versioning. This version number is overridden by Codemagic.
version: 1.0.1+2

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.2
  cupertino_icons: ^1.0.4 # iOS-style icons
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.2
  dio_cache_interceptor_db_store: ^4.1.0
  drift: ^1.6.0
  equatable: ^2.0.3
  flutter_cache_manager: ^3.3.0
  google_fonts: ^2.2.0
  http: ^0.13.3
  json_annotation: ^4.4.0
  just_audio: ^0.9.18
  path: ^1.8.0
  path_provider: ^2.0.7
  provider: ^6.0.1
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.12
  sqlite3_flutter_libs: ^0.5.7 # Workaround to open sqlite3 on old Android versions
  video_player: ^2.2.11
  wc_flutter_share: ^0.4.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  drift_dev: ^1.6.0
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

#flutter_icons:
#  android: true
#  ios: true
#  image_path: assets/icon/icon.png

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - config/
    - assets/icon/icon.png
    - assets/images/
    - assets/images/quote-bg-dark-black-700px.png
    - assets/images/quote-bg-dark-brown-700px.png
    - assets/images/quote-bg-light-700px.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
