name: patta
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

publish_to: 'none'

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  cached_network_image: ^3.2.0
  json_annotation: ^4.4.0
  http: ^0.13.3
  wc_flutter_share: ^0.4.0
  path: ^1.8.0
  path_provider: ^2.0.7
  drift: ^1.0.0
  sqlite3_flutter_libs: ^0.5.1 # previously moor_ffi
  provider: ^6.0.1
  equatable: ^2.0.3
  connectivity: ^3.0.6
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.2
  dio_cache_interceptor_db_store: ^4.1.0
  flutter_cache_manager: ^3.3.0
  video_player: ^2.2.11
  just_audio: ^0.9.18
  google_fonts: ^2.2.0
  shared_preferences: ^2.0.12
  settings_ui: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.0
  json_serializable: ^6.1.1
  drift_dev: ^1.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
    - config/
    - assets/icon/icon.png
    - assets/images/
    - assets/images/quote-bg-dark-700px.png
    - assets/images/quote-bg-light-700px.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
